//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paper()
        {
            this.files = new HashSet<file>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public int Author { get; set; }
        public Nullable<System.DateTime> DateOfPublishing { get; set; }
        public Nullable<int> Editor { get; set; }
        public int STATUS_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        public virtual status status { get; set; }
        public virtual user author_user { get; set; }
        public virtual user editor_user { get; set; }
    }
}
